"""Initial Migration

Revision ID: ff5e11632c95
Revises:
Create Date: 2018-07-14 12:03:58.867357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff5e11632c95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.create_table('tag',
    sa.Column('id', postgresql.UUID(), server_default=sa.text(u'uuid_generate_v4()'), nullable=False),
    sa.Column('vendor_id', postgresql.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_vendor_id'), 'tag', ['vendor_id'], unique=False)
    op.create_table('meta',
    sa.Column('tag_id', postgresql.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'key')
    )
    op.create_index(op.f('ix_meta_value'), 'meta', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_value'), table_name='meta')
    op.drop_table('meta')
    op.drop_index(op.f('ix_tag_vendor_id'), table_name='tag')
    op.drop_table('tag')
    op.execute('DROP EXTENSION "uuid-ossp"')
    # ### end Alembic commands ###
